// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU31HEpoHedOIyM7dFrYY2QtbUOG_caZc',
    appId: '1:648981381198:web:f20bd4e16fe9b0e818431f',
    messagingSenderId: '648981381198',
    projectId: 'farmfinancer',
    authDomain: 'farmfinancer.firebaseapp.com',
    storageBucket: 'farmfinancer.appspot.com',
    measurementId: 'G-BNLCY8QCD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jAcM6qJa_VaGbAIKfNDtAYDP7_NiZsA',
    appId: '1:648981381198:android:d99640946c8a91b918431f',
    messagingSenderId: '648981381198',
    projectId: 'farmfinancer',
    storageBucket: 'farmfinancer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpyEXW4uHKeFXuqeHPkjn0PRfYK6LzyWQ',
    appId: '1:648981381198:ios:667f81e0646a1e6d18431f',
    messagingSenderId: '648981381198',
    projectId: 'farmfinancer',
    storageBucket: 'farmfinancer.appspot.com',
    iosBundleId: 'com.example.farmFinancer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpyEXW4uHKeFXuqeHPkjn0PRfYK6LzyWQ',
    appId: '1:648981381198:ios:910829b59aba263518431f',
    messagingSenderId: '648981381198',
    projectId: 'farmfinancer',
    storageBucket: 'farmfinancer.appspot.com',
    iosBundleId: 'com.example.farmFinancer.RunnerTests',
  );
}
